name: Test Backend
on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          lfs: 'true'
      - name: Mock manifest
        run: |
          echo '{
            "services": {
              "example-app": {
                "name": "farm-ng-amiga-autonomus-navigation",
                "type": "app",
                "args": [
                  "--config /opt/farmng/config.json", "--port 8042"
                ],
                "autostart": true,
                "http_gui_port": 8042,
                "display_name": "Monitor App"
              }
            }
          }' > manifest.json
      - name: Install packages
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install farm_ng_amiga-2.3.4-py3-none-any.whl
          pip install -r requirements.txt
      - name: Pytest
        run: |
          source .venv/bin/activate
          cd backend/
          PYTHONPATH="." pytest
