name: Test cameraBackend
on:
  push:
    paths:
      - 'amiga-app/backend/cameraBackend/**'
      - 'amiga-app/backend/tests**'
  pull_request:
    paths:
      - 'amiga-app/backend/cameraBackend/**'
      - 'amiga-app/backend/tests**'
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x
          architecture: x64
          lfs: 'true'
      - name: checkoutLFS
        uses: actions/checkout@v2
        run: git lfs pull
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          cd amiga-app/
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install farm_ng_amiga-2.3.4-py3-none-any.whl
          pip install -r requirements.txt
      - name: Pytest
        run: |
          cd amiga-app/
          source .venv/bin/activate
          cd backend/
          PYTHONPATH="." pytest
