name: Lint mypy

on:
  push:
    paths:
      - '**/requirements.txt'
      - '**/*.py'
  pull_request:
    paths:
      - '**/requirements.txt'
      - '**/*.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          cd amiga-app/
          python3 -m venv .venv
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run mypy
        run: |
          cd amiga-app/
          source .venv/bin/activate
          PYTHONPATH=backend mypy backend/*.py